version: '3.1'
services:
  frontend:
    container_name: frontend
    build: .
    restart: always
    ports:
      - 80:3000
    environment:
      REACT_APP_URL_SERVER: 'http://LB-Aplication-2078111387.us-east-1.elb.amazonaws.com:8080'