version: '3.1'
services:
  backend:
    container_name: backend
    build: .
    restart: always
    ports:
      - 8080:5000
    environment:
      NODE_ENV: Prod
      DB_PROVIDER: DynamoDB
      DB_CONNECTION: '{ "accessKeyId": "ASIA3K4PKUDY3OFZXYOZ", "secretAccessKey": "wE/S5iVMzw1ONvchm/GwB5iS6MJo0G3xfkKnQxCZ", "sessionToken": "FwoGZXIvYXdzEA4aDGe1WUg2BLP+FjkyziLIAeQXQqQkL2kLhrX6ZEw8Bvu7Y1yWAL28KBndJi/2I6kcJUAc99WF4tj1SgKvd5Fm5jHV8gEZHffybAcpOL7d7Nbbj0qEtaJD/39g74N3LRRroD0+lEN7T6+Wnl2b1O4tPwVAeByTNbya6u6X2Vg0Q3gj2JUHObQ2beU67wmjUTCoXNDGW50EgtG834btqw0tcuGeIzRQbUTguQ13CTEt5N+3+8rtjYFBwG0QUhDnWC3XJGsl0deiN96Rcgsk92qltvl9dyb6CE+aKPW8xKMGMi2BKFwR1WhGy8oXHtxHBUpy3KS1XxIoGVqVZPtX1QCl84xAUTnrLr5DSqKQadk=", "region": "us-east-1"}'